const data = [
    {
        id: 1,
        ratio: "Working Capital",
        description: "Represents a company's ability to pay its current liabilities with its current assets",
        formula: "Current Assets - Current Liabilties"
    },
    {
        id: 2,
        ratio: "Quick Ratio",
        description: "Measures a company’s ability to pay off short-term liabilities with a ready cash value",
        formula: "(Current assets – Inventories) / Current liabilities"
    },
    {
        id: 3,
        ratio: "Debt-to-Equity Ratio",
        description: "Calculates the weight of total debt and financial liabilities against shareholders’ equity",
        formula: "Total Liabilities / Shareholder’s Equity"
    },
    {
        id: 4,
        ratio: "Earning-Per-Share Ratio (EPS)",
        description: "Measures the amount of net income earned for each oustanding share",
        formula: "Net earnings / Total shares outstanding"
    },
    {
        id: 5,
        ratio: "Price-Per-Earning Ratio (P/E)",
        description: "Compares a company’s share price to its Earnings per Share. It reflects investors' assessments of the company's future earnings",
        formula: "Share price / Earnings per share"
    },
    {
        id: 6,
        ratio: "Price-to-Book Ratio (P/B)",
        description: "Measures the market's valuation of a company relative to its book value, often used together with Return on Equity (ROE)",
        formula: "Market Price per Share / Book Value Per Share "
    },
    {
        id: 7,
        ratio: "Price/Earnings-to-Growth Ratio (PEG)",
        description: "Enhances the P/E ratio by adding in expected earnings growth into the calculation, thus, reflecting a better indicator of a stock's true value",
        formula: "P/E Ratio / EPS Growth"
    },
    {
        id: 8,
        ratio: "Return of Equity (ROE)",
        description: "Measures the amount of profit generated by a company with the money invested by the shareholders",
        formula: "Net Income / Shareholder's Equity"
    },
    {
        id: 9,
        ratio: "Free Cash Flow",
        description: "Represents the cash available for the company to repay creditors or pay dividends and interest to investors.",
        formula: "Operating Cash Flow - Capital Expenditure"
    },
]


export default data;